const casteCategories = {
  "Scheduled Castes (SC)": [
    "Ager",
    "Anamook",
    "Aaremala",
    "Aarwa Mala",
    "Bahna",
    "Bakad",
    "Bant",
    "Balahi",
    "Basor",
    "Bedar",
    "Bhaambi",
    "Chamaar",
    "Dhor",
    "Mang",
    "Matang",
    "Kori",
    "Mahar",
    "Mala",
    "Paasi",
    "Saansi",
  ],
  "Scheduled Tribes (ST)": [
    "Andh",
    "Baiga",
    "Barda",
    "Bavacha",
    "Bamcha",
    "Bhaina",
    "Bharia Bhumia",
    "Bhattra",
    "Bhil",
    "Binjhwar",
    "Birhul",
    "Birhor",
    "Dhanka",
    "Dhanwar",
    "Dhodia",
    "Dubla Talavia",
    "Gamit",
    "Gamta",
    "Gavit",
    "Mavchi",
    "Padvi",
    "Gond",
    "Halba",
    "Kathodi",
    "Kawar",
    "Kol",
    "Kolam",
    "Koli",
    "Kokna",
    "Koya",
    "Naikda",
    "Oraon",
    "Pardhan",
    "Pardhi",
    "Parja",
    "Patelia",
    "Pomla",
    "Rathwa",
    "Sawar",
    "Thakar",
    "Thoti",
    "Varli",
    "Vitolia",
  ],
  "Other Backward Classes (OBC)": [
    "Alitkar",
    "Bagdi",
    "Badia",
    "Bajania",
    "Bajigar",
    "Buttal",
    "Bhand",
    "Chappar Bhand",
    "Bavaiya",
    "Targal",
    "Bhavin",
    "Bhisti",
    "Pakhali",
    "Bari",
    "Barai",
    "Beriya",
    "Besdeva",
    "Bhanta",
    "Chamatha",
    "Charan",
    "Chippa",
    "Das",
    "Dangadidas",
    "Devdig",
    "Dholi",
    "Hashmi",
    "Gochaki",
    "Gurav",
    "Halepaik",
    "Jogin",
    "Jangam",
    "Kumbhar",
    "Kunbi",
    "Lad",
    "Lingayat Mali",
    "Mali",
    "Navi",
    "Naavi",
    "Panchal",
    "Parit",
    "Rangari",
    "Sutar",
    "Tambat",
    "Wani",
    "Yadav",
  ],
  "Special Backward Classes (SBC)": [
    "Gowari",
    "Koshti",
    "Halba Koshti",
    "Sali",
    "Swakul Sali",
    "Lad Koshti",
    "Gadhhewal Koshti",
    "Deshkar Koshti",
    "Salewar",
    "Padma Shali",
    "Koli",
    "Munnerwar",
    "Telagu Munnur",
    "Munnurwaad",
  ],
  "Vimukta Jati (VJ)": [
    "Berad",
    "Bestar",
    "Bhamata",
    "Kaikadi",
    "Katabu",
    "Lamani",
    "Raj Pardhi",
    "Ramoshi",
    "Vadar",
    "Waghari",
    "Chhapparband",
  ],
  "Nomadic Tribes - B (NT-B)": [
    "Gosavi",
    "Beldar",
    "Bharaadi",
    "Bhute Bhope",
    "Chitrakathi",
    "Garudi",
    "Lohar",
    "Golla",
    "Gondhali",
    "Gopal",
    "Helave",
    "Joshi",
    "Kolhati",
    "Mairal",
    "Masanjogi",
    "Nandiwale",
    "Pangul",
    "Rawal",
    "Sikkalgar",
    "Thakar",
    "Vaidu",
    "Vasudeo",
    "Bhoi",
    "Bahurupi",
    "Thelari",
    "Otari",
  ],
  "Nomadic Tribes - C (NT-C)": ["Dhangar"],
  "Nomadic Tribes - D (NT-D)": ["Vanjari"],
};

export default casteCategories;
